### ISSUE TITLE
No instructions on how to push the Docker image

### ISSUE THREAD

**Issue by patrocinio** [ibm-cloud-architecture/microservices-netflix-eureka#9]
When I run the deploy to Bluemix command, I get the following message

```
Eduardos-MBP:bluemix edu$ ./deploy-container-group.sh
Looking up Bluemix registry images
Registry Image Not Found.  Attempting to push from Local Docker
Local Registry Image Not Found.  Exiting...
```

**Comment by jesusmah** [comment]
@patrocinio have you executed build-microservice.sh script with the -d flag? If so, there is a problem since a local docker image with the correct name should've been created but you are seeing an error stating otherwise. If you have not executed the script with that -d flag, then the problem is that you have not build the docker image locally and so we need to update the instructions to make sure the user executes the build-microservice.sh script with the -d flag if they plan to deploy the app onto Bluemix.
Thanks

**Comment by jesusmah** [comment]
This issue might well happen in other repos since READMEs seems to be all the same...

**Comment by patrocinio** [comment]
Hello @jesusmah Thanks for clarifying the '-d' option. Closing this issue...
